In [15]:
import numpy

In [17]:
data = np.genfromtxt("file.csv",delimiter = ",",skip_header = 1)
data

array([[39., 13.,  4., ...,  0., 40.,  0.],
       [50., 13.,  4., ...,  0., 13.,  0.],
       [38.,  9.,  4., ...,  0., 40.,  0.],
       ...,
       [48., 13.,  4., ...,  0., 58.,  1.],
       [40., 10.,  4., ...,  0., 40.,  0.],
       [39., 13.,  4., ...,  0., 50.,  1.]])

In [18]:
data.shape

(1000, 8)

In [30]:
new_record = [[50,9,4,1,0,0,40,0]]

In [33]:
census = np.concatenate((data,new_record),axis = 0)

In [ ]:
# age, education-num, race, sex, capital gain, capital- loss, hours per week, income

In [45]:
age = census[:,0]
age
min_age = min(age)
min_age
max_age= max(age)
age_mean  = numpy.average(age)

In [46]:
census[:,2]

array([4., 4., 4., ..., 4., 4., 4.])

In [47]:
#Creating new subsets based on 'race'
race_0=census[census[:,2]==0]
race_1=census[census[:,2]==1]
race_2=census[census[:,2]==2]
race_3=census[census[:,2]==3]
race_4=census[census[:,2]==4]


In [48]:
race_0

array([[34.,  4.,  0.,  1.,  0.,  0., 45.,  0.],
       [35., 10.,  0.,  0.,  0.,  0., 40.,  0.],
       [60.,  6.,  0.,  0.,  0.,  0., 10.,  0.],
       [51.,  9.,  0.,  1.,  0.,  0., 40.,  0.],
       [25., 10.,  0.,  0.,  0.,  0., 20.,  0.],
       [20.,  9.,  0.,  1.,  0.,  0., 48.,  0.],
       [23., 10.,  0.,  0.,  0.,  0., 25.,  0.],
       [29.,  9.,  0.,  1.,  0.,  0., 40.,  0.],
       [27., 12.,  0.,  1.,  0.,  0., 40.,  0.],
       [31., 12.,  0.,  0.,  0.,  0., 40.,  0.]])

In [52]:
#Finding the length of the above created subsets
len_0=len(race_0)
len_1=len(race_1)
len_2=len(race_2)
len_3=len(race_3)
len_4=len(race_4)

#Printing the length of the above created subsets
print('Race_0: ', len_0)
print('Race_1: ', len_1)
print('Race_2: ', len_2)
print('Race_3: ', len_3)
print('Race_4: ', len_4)

#Storing the different race lengths with appropriate indexes
race_list=[len_0, len_1,len_2, len_3, len_4]

#Storing the race with minimum length into a variable 
minority_race=race_list.index(min(race_list))
minority_race

Race_0:  10
Race_1:  27
Race_2:  110
Race_3:  6
Race_4:  848


3

In [53]:
#Subsetting the array based on the age 
senior_citizens=census[census[:,0]>60]
#calculating sum
working_hours_sum=senior_citizens.sum(axis=0)[6]
senior_citizens_len=len(senior_citizens)
avg_working_hours=working_hours_sum/senior_citizens_len
print((avg_working_hours))

#Creating an array based on 'education' column
high=census[census[:,1]>10]
avg_pay_high=high[:,7].mean()
print(avg_pay_high)

#Creating an array based on 'education' column
low=census[census[:,1]<=10]
avg_pay_low=low[:,7].mean()
print(avg_pay_low)

31.42622950819672
0.42813455657492355
0.13649851632047477


In [56]:
numpy.average(senior_citizens[:,6])

31.42622950819672